name = "yungen_dev"
version = "0.1.0"
target = "erlang"
description = "personal blog, built with Gleam + Blogatto"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_time = ">= 1.7.0 and < 2.0.0"
lustre = ">= 5.6.0 and < 6.0.0"
blogatto = ">= 7.0.0 and < 8.0.0"
argv = ">= 1.1.0 and < 2.0.0"
simplifile = ">= 2.5.0 and < 3.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
str = ">= 2.1.1 and < 3.0.0"
frontmatter = ">= 1.0.1 and < 2.0.0"
smalto_lustre = ">= 3.0.0 and < 4.0.0"
mork = ">= 1.12.1 and < 2.0.0"
gleam_json = ">= 2.0.0 and < 4.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
shellout = ">= 1.6.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

