baseURL = 'https://yungen.dev'
languageCode = 'en-us'
title = 'yungen'
theme = 'hugo-theme-nostyleplease'

[params]
  [params.theme_config]
    # appearance        = "dark"
    # back_home_text    = ".."
    # date_format       = "2006-01-02"
    # isListGroupByDate = false
    # isShowFooter      = false
    titleLinkEnable   = true
    titleLink         = "/about"
[frontmatter]
lastmod = ["lastmod" ,':fileModTime']
